version: "3.8"
services:
  backend-dev:
    image: cosmtrek/air
    working_dir: /home/app
    ports:
      - 5000:5000
    volumes:
      - ./:/home/app
    env_file: .env
    depends_on:
      - db

  db:
    image: mysql
    container_name: "mysql_db"
    restart: always
    environment:
      MYSQL_DATABASE: egoist
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
    driver: local
